[[edge_functions]]
  path = "/receita/*"
  function = "metadata"

[[edge_functions]]
  path = "/pack/*"
  function = "metadata"

[[edge_functions]]
  path = "/infoproduto/*"
  function = "metadata"

[[edge_functions]]
  path = "/upsell/*"
  function = "metadata"

[[edge_functions]]
  path = "/categoria/*"
  function = "metadata"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200