[build]
  command = "npm run build"
  publish = "dist"

[[edge_functions]]
  path = "/receita/*"
  function = "metadata"

[[edge_functions]]
  path = "/pack/*"
  function = "metadata"

[[edge_functions]]
  path = "/infoproduto/*"
  function = "metadata"

[[edge_functions]]
  path = "/categoria/*"
  function = "metadata"

[[edge_functions]]
  path = "/capa/*"
  function = "capa-imagem"